# Generated by Django 3.2.18 on 2023-03-11 16:08

import datetime
from django.db import migrations, models
import django.db.models.deletion
import month.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teacher', '0001_initial_migration'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discipline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='name')),
                ('abbr', models.CharField(max_length=50, unique=True, verbose_name='abbreviation')),
                ('slug', models.CharField(max_length=200, unique=True, verbose_name='slug')),
            ],
            options={
                'verbose_name': 'discipline',
                'verbose_name_plural': 'disciplines',
            },
        ),
        migrations.CreateModel(
            name='EduOrganization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='name')),
                ('abbr', models.CharField(max_length=50, unique=True, verbose_name='abbreviation')),
            ],
            options={
                'verbose_name': 'education organization',
                'verbose_name_plural': 'education organizations',
            },
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_start', models.DateField(default=datetime.date.today, verbose_name='date education start')),
                ('date_end', models.DateField(default=datetime.date.today, verbose_name='date education end')),
                ('slug', models.CharField(max_length=200, unique=True, verbose_name='slug')),
            ],
            options={
                'verbose_name': 'semester',
                'verbose_name_plural': 'semesters',
            },
        ),
        migrations.CreateModel(
            name='Speciality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='name')),
                ('abbr', models.CharField(max_length=50, unique=True, verbose_name='abbreviation')),
                ('edu_organizations', models.ManyToManyField(related_name='specialities', to='journal.EduOrganization', verbose_name='education organizations')),
            ],
            options={
                'verbose_name': 'speciality',
                'verbose_name_plural': 'specialities',
            },
        ),
        migrations.CreateModel(
            name='StudentGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('abbr', models.CharField(max_length=50, verbose_name='abbreviation')),
                ('slug', models.CharField(max_length=200, unique=True, verbose_name='slug')),
                ('date_start_edu', month.models.MonthField(verbose_name='date education start')),
                ('date_end_enu', month.models.MonthField(verbose_name='date education end')),
                ('is_commercial', models.BooleanField(default=False, verbose_name='is commercial')),
                ('edu_organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_groups', to='journal.eduorganization', verbose_name='education organization')),
                ('speciality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_groups', to='journal.speciality', verbose_name='speciality')),
            ],
            options={
                'verbose_name': 'student group',
                'verbose_name_plural': 'student groups',
            },
        ),
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('slug', models.CharField(max_length=200, unique=True, verbose_name='slug')),
                ('discipline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journals', to='journal.discipline', verbose_name='discipline')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journals', to='journal.semester', verbose_name='semester')),
                ('student_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journals', to='journal.studentgroup', verbose_name='student group')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journals', to='teacher.teacher', verbose_name='teacher')),
            ],
            options={
                'verbose_name': 'journal',
                'verbose_name_plural': 'journals',
            },
        ),
        migrations.AddField(
            model_name='discipline',
            name='specialities',
            field=models.ManyToManyField(related_name='disciplines', to='journal.Speciality', verbose_name='specialities'),
        ),
    ]
