# Generated by Django 3.2.18 on 2023-03-13 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0001_initial_migrations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discipline',
            name='slug',
            field=models.CharField(blank=True, help_text='must use english letters, and dash signs for spaces (autogenerate)', max_length=200, unique=True, verbose_name='slug'),
        ),
        migrations.AlterField(
            model_name='journal',
            name='slug',
            field=models.CharField(blank=True, help_text='must use english letters, and dash signs for spaces (autogenerate)', max_length=200, unique=True, verbose_name='slug'),
        ),
        migrations.AlterField(
            model_name='studentgroup',
            name='slug',
            field=models.CharField(blank=True, help_text='must use english letters, and dash signs for spaces (autogenerate)', max_length=200, unique=True, verbose_name='slug'),
        ),
    ]
