# Generated by Django 3.2.18 on 2023-03-13 12:58

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('student', '0001_initial_migrations'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('journal', '0002_create_lesson_migrations'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(choices=[('+', 'Present'), ('none', 'Absent'), ('none (reas.)', 'Absent (for a good reason)'), ('?', 'Not marked')], default='?', max_length=50, verbose_name='Оценка посещаемости')),
            ],
            options={
                'verbose_name': 'attendance',
                'verbose_name_plural': 'attendance',
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('date', models.DateField(default=datetime.date.today, verbose_name='lesson date')),
                ('number', models.IntegerField(blank=True, verbose_name='number of lesson')),
                ('theme', models.TextField(blank=True, max_length=200, verbose_name='theme of lesson')),
                ('type', models.CharField(choices=[('lec.', 'Lecture'), ('LW', 'Laboratory work'), ('PW', 'Practical work')], default='lec.', max_length=50, verbose_name='type of lesson')),
                ('journal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='journal.journal', verbose_name='journal')),
            ],
            options={
                'verbose_name': 'lesson',
                'verbose_name_plural': 'lessons',
            },
        ),
        migrations.CreateModel(
            name='AttendanceComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(max_length=500, verbose_name='message')),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='publish date')),
                ('is_checked', models.BooleanField(default=False, verbose_name='is read')),
                ('media', models.FileField(upload_to='', verbose_name='file')),
                ('attendance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_comments', to='lesson.attendance', verbose_name='attendance')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_comments', to=settings.AUTH_USER_MODEL, verbose_name='author')),
            ],
            options={
                'verbose_name': 'attendance comment',
                'verbose_name_plural': 'attendance comments',
                'ordering': ['pub_date'],
            },
        ),
        migrations.AddField(
            model_name='attendance',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance', to='lesson.lesson', verbose_name='lesson'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance', to='student.student', verbose_name='student'),
        ),
        migrations.AddConstraint(
            model_name='attendance',
            constraint=models.UniqueConstraint(fields=('lesson', 'student'), name='unique attendance grade field'),
        ),
    ]
